# -*- coding: utf-8 -*-
"""
Created on Sat Nov 13 19:05:57 2021

@author: ethan
"""
word_list = {
    "cauchy bunyakovsky schwarz": "NE112",
    "gram schmidt": "NE112",
    "stoichiometry": "NE121",
    "pendar mahmoudi": "NE111",
    "boolean": "NE111",
    "proffesional engineers of ontario": "NE109",
    "crystallinity": "NE100",
    "base centered cubic": "NE100",
    "face centered cubic": "NE100",
    "acids and bases": "NE121",
    "laura deakin": "NE121",
    "good day for those of you who do not know me": "NE112",
    "pu chen": "NE100",
    "howard siu": "NE109",
    "mohammad kohandel": "NE117",
    "calorimetry": "NE121",
    "buffers": "NE121",
    "eigen vectors": "NE112",
    "while loops": "NE111",
    "if statements": "NE111",
    "ahmad ghavami": "NE100",
    "douglas harder": "NE112",
    "ipython": "NE111",
    "nanofabrication": "NE100",
    "bravais lattice": "NE100",
    "orthogonal vector": "NE112",
    "orthonormal vector": "NE112",
    "mean value theorem": "NE117",
    "integral": "NE117",
    "indefinite integral": "NE117",
    "definite integral": "NE117",
    "row echelon": "NE112",
    "trigonometric substition": "NE117",
    "tort law": "NE109",
    "sustainability": "NE109",
    "integration by substitution": "NE117",
    "integration by part": "NE117",
    "free energy": "NE121",
    "entropy": "NE121",
    "ideal gases": "NE121",
    "numpy": "NE111",
    "iuvoderm": "NE109",
    "common and civil law": "NE109",
    "plasma enhanced chemical vapor deposition": "NE100",
    "chemical vapor deposition": "NE100",
    "wet etching": "NE100",
    "dry etching": "NE100",
    "eigen values": "NE112",
    "eigen spaces": "NE112",
    "metal deposition": "NE100",
    "silicon oxide deposition": "NE100",
    "substrate": "NE100",
    "nanometer": "NE100",
    "nanosecond": "NE100",
    "solidworks": "NE100",
    "engineering design": "NE100",
    "energy band": "NE121",
    "micropippeting": "NE100",
    "dilution": "NE100",
    "soldering": "NE100",
    "squeeze theorem": "NE117",
    "carbon nanotube": "NE109",
    "quantum nanodot": "NE109",
    "quantum nano center": "NE121",
    "pathways": "NE121",
    "is that right": "NE100" 
    
    }
    
#Categories: NE 100, NE 111, NE 109, NE 121, MATH 117, NE 112
